### ISSUE TITLE
 1.3.2 NetworkingType 网络请求问题

### ISSUE THREAD

**Issue by haoXu1990** [tospery/SWFrame#1]
您好,我看您的的库很方便准备学习下可是我在使用 NetworkingType 的时候发现网络请求无法发送

SWFrame 版本: 1.3.2
使用样例
第一步:
定义一个 Networking 继承 NetworkingType 
struct QIMNetworking: NetworkingType {
    var provider: MoyaProvider<QIMAPI>
    typealias Target = QIMAPI
}
第二步
extension ProviderType {
    private var qimingNetworking: QIMNetworking {
        return QIMNetworking.init(provider: MoyaProvider<QIMAPI>(endpointClosure: QIMNetworking.endpointClosure,
                                                                 requestClosure: QIMNetworking.requestClosure,
                                                                 stubClosure: QIMNetworking.stubClosure,
                                                                 plugins: QIMNetworking.plugins))
    }

   func fetchUser(xxx) -> Single<Data> {
      return self.qimingNetworking.request(xxxx)
  }
}

经过测试发现直接用 MoyaProvider<QIMAPI>()  这样是可以请求的, 
请问能指点下吗

**Comment by tospery** [comment]
这里有一个示例，你可以参考一下:
https://github.com/tospery/SWHub
